### PR TITLE
Empty Example project

### PR DESCRIPTION
**Pull request by mattThousand**

### CODE REVIEW

**Comment by ateliercw** [comment]
:+1: can you add swiftlint as well?

**Comment by mattThousand** [comment]
@ateliercw you bet'cha

**Comment by mattThousand** [comment]
@ateliercw done-zo. note that I added a couple of things in `.swiftlint.yml`, not sure what your preference/dogma is w/ regard to those rules

**Review by ateliercw — APPROVED** [review]

**Comment by mattThousand** [comment]
... does reviewer or author merge...?

**Pull request merged**
